# Use postgres/example user/password credentials
version: '3.1'

networks:
  db-network:
    driver: bridge

services:
  inst:
    image: inst
    restart: always
    ports:
      - 80:2020
      - 8000:8000
    networks:
      - db-network
    environment:
      - SPRING_DATA_SOURCE_URL=jdbc:postgresql://db:5432/postgres

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - db-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081